version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    restart: always  # Automatically restart the app if it crashes
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always  # Automatically restart the database if it crashes

volumes:
  postgres-data:
